name: Node.js CD

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_on_push:
    name: redeploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
          mkdir -p ~/.ssh
          ssh-keyscan 13.50.5.149 >> ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh -i ssh_key ubuntu@13.50.5.149 << 'EOF'
            cd CI-CD-node/
            git pull
            npm install
            pm2 restart CI-CD-node
          EOF
